//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.DB.AMSWebService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://201.228.212.66/WebService", ConfigurationName="AMSWebService.AMS_WebserviceSoap")]
    public interface AMS_WebserviceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://201.228.212.66/WebService/RequestSQL", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet RequestSQL(string user, string pass, string sql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://201.228.212.66/WebService/SingleDataSQL", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SingleDataSQL(string user, string pass, string sql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://201.228.212.66/WebService/NonQuerySQL", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int NonQuerySQL(string user, string pass, string sql);
        
        // CODEGEN: Parameter 'blob' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://201.228.212.66/WebService/NonQueryBlobSQL", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AMS.DB.AMSWebService.NonQueryBlobSQLResponse NonQueryBlobSQL(AMS.DB.AMSWebService.NonQueryBlobSQLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://201.228.212.66/WebService/RecordExistSQL", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool RecordExistSQL(string user, string pass, string sql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://201.228.212.66/WebService/TransactionSQL", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        bool TransactionSQL(string user, string pass, object[] sql);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="NonQueryBlobSQL", WrapperNamespace="http://201.228.212.66/WebService", IsWrapped=true)]
    public partial class NonQueryBlobSQLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://201.228.212.66/WebService", Order=0)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://201.228.212.66/WebService", Order=1)]
        public string pass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://201.228.212.66/WebService", Order=2)]
        public string sql;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://201.228.212.66/WebService", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] blob;
        
        public NonQueryBlobSQLRequest() {
        }
        
        public NonQueryBlobSQLRequest(string user, string pass, string sql, byte[] blob) {
            this.user = user;
            this.pass = pass;
            this.sql = sql;
            this.blob = blob;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="NonQueryBlobSQLResponse", WrapperNamespace="http://201.228.212.66/WebService", IsWrapped=true)]
    public partial class NonQueryBlobSQLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://201.228.212.66/WebService", Order=0)]
        public int NonQueryBlobSQLResult;
        
        public NonQueryBlobSQLResponse() {
        }
        
        public NonQueryBlobSQLResponse(int NonQueryBlobSQLResult) {
            this.NonQueryBlobSQLResult = NonQueryBlobSQLResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AMS_WebserviceSoapChannel : AMS.DB.AMSWebService.AMS_WebserviceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AMS_WebserviceSoapClient : System.ServiceModel.ClientBase<AMS.DB.AMSWebService.AMS_WebserviceSoap>, AMS.DB.AMSWebService.AMS_WebserviceSoap {
        
        public AMS_WebserviceSoapClient() {
        }
        
        public AMS_WebserviceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AMS_WebserviceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AMS_WebserviceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AMS_WebserviceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet RequestSQL(string user, string pass, string sql) {
            return base.Channel.RequestSQL(user, pass, sql);
        }
        
        public string SingleDataSQL(string user, string pass, string sql) {
            return base.Channel.SingleDataSQL(user, pass, sql);
        }
        
        public int NonQuerySQL(string user, string pass, string sql) {
            return base.Channel.NonQuerySQL(user, pass, sql);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AMS.DB.AMSWebService.NonQueryBlobSQLResponse AMS.DB.AMSWebService.AMS_WebserviceSoap.NonQueryBlobSQL(AMS.DB.AMSWebService.NonQueryBlobSQLRequest request) {
            return base.Channel.NonQueryBlobSQL(request);
        }
        
        public int NonQueryBlobSQL(string user, string pass, string sql, byte[] blob) {
            AMS.DB.AMSWebService.NonQueryBlobSQLRequest inValue = new AMS.DB.AMSWebService.NonQueryBlobSQLRequest();
            inValue.user = user;
            inValue.pass = pass;
            inValue.sql = sql;
            inValue.blob = blob;
            AMS.DB.AMSWebService.NonQueryBlobSQLResponse retVal = ((AMS.DB.AMSWebService.AMS_WebserviceSoap)(this)).NonQueryBlobSQL(inValue);
            return retVal.NonQueryBlobSQLResult;
        }
        
        public bool RecordExistSQL(string user, string pass, string sql) {
            return base.Channel.RecordExistSQL(user, pass, sql);
        }
        
        public bool TransactionSQL(string user, string pass, object[] sql) {
            return base.Channel.TransactionSQL(user, pass, sql);
        }
    }
}
